<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogixonBackend.Domain\LogixonBackend.Domain.csproj" />
    <ProjectReference Include="..\LogixonBackend.Infra\LogixonBackend.Infra.csproj" />
  </ItemGroup>

</Project>
